apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockerhub-pv
  namespace: registry
  labels:
    type: local
spec:
  capacity:
    storage: 500Gi
  claimRef:
    name: dockerhub-pvc
    namespace: registry
  accessModes:
  - ReadWriteOnce
  storageClassName: csi-rawfile-default
  local:
    path: /var/snap/k8s/common/rawfile-storage/dockerhub
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - meystgdkuhost01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dockerhub-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: csi-rawfile-default
